build: false

image:
  - Visual Studio 2017

environment:
    PYTHON_HOME: "C:\\Python37"

    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15
          ARCH: x86
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15
          ARCH: x86_64

install:
  - set PATH=%PYTHON_HOME%;%PYTHON_HOME%/Scripts/;%PATH%
  - pip.exe install conan --upgrade
  - pip.exe install conan_package_tools bincrafters-package-tools
  - C:\msys64\usr\bin\bash -lc "pacman -S automake-wrapper autoconf --noconfirm --needed"
  - conan user # It creates the conan data directory

test_script:
  - python build.py
